spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?autoReconnect=true
    username: postgres
    password: postgres
    continue-on-error: true
    hikari:
      initialization-fail-timeout: 0

jpa:
  database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  generate-ddl: true
  show-sql: true
  hibernate:
    ddl-auto: create

